services:
  - type: web
    name: cascos-app-pc
    runtime: node
    plan: free
    rootDir: cascos-app-pc
    buildCommand: npm install -g pnpm && pnpm install --no-frozen-lockfile && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_LIVEKIT_URL
        value: wss://casco-nmlttzpb.livekit.cloud
      - key: NEXT_PUBLIC_LIVEKIT_API
        value: https://casco-nmlttzpb.livekit.cloud
      - key: NEXT_PUBLIC_LIVEKIT_API_KEY
        value: APIpjmsEDHpxCN8
      - key: NEXT_PUBLIC_DEFAULT_ROOM
        value: jhoan
      - key: LIVEKIT_API_SECRET
        sync: false
